baseURL = 'https://khatunajannatcse.github.io/hugo-academic-site/'
languageCode = 'en-us'
title = 'Academic Portfolio'

[module]
  [[module.imports]]
    path = 'github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5'

[outputs]
  home = ["HTML", "RSS"]