baseURL = 'https://khatunajannatcse.github.io/hugo-academic-site/'
languageCode = 'en-us'
title = 'Khatun A Jannat'

[params]
  author = "Khatun A Jannat"
  role = "MSc Student in CSE (Data Science)"

[[menu.main]]
  name = "About"
  url = "#about"
  weight = 10

[[menu.main]]
  name = "Research"
  url = "#research"
  weight = 20

[[menu.main]]
  name = "Projects"
  url = "#projects"
  weight = 30